version: '3'

networks:
  laravel:

services:
  redis:
    image: redis:alpine

  postgres:
    image: postgres:9.5-alpine
    container_name: pgsql
    restart: always
    volumes:
      - "./:/postgres/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - laravel
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/gr-plan
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/gr-plan
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:2.2.6
    volumes:
      - ./:/var/www/gr-plan
    working_dir: /var/www/gr-plan
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:lts
    volumes:
      - ./:/var/www/gr-plan
    working_dir: /var/www/gr-plan
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/gr-plan
    depends_on:
      - postgres
    working_dir: /var/www/gr-plan
    entrypoint: ['php', '/var/www/gr-plan/artisan']
    networks:
      - laravel

volumes:
  postgres: {}